<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <RootNamespace>Rees.Wpf</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.Metrics" Version="5.6.0" />
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    </ItemGroup>

</Project>
